#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
if [ -d /sys/kernel/security/apparmor ] && [ "$(cat /proc/self/attr/current)" != "unconfined" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
fi

# Re-exec in the host namespace
if [ -z "${LXD_HOSTFS:-""}" ]; then
    PWD=$(pwd)
    if [ "${PWD}" = "/var/lib/snapd/void" ]; then
        PWD="$(readlink -f "/proc/${PPID}/cwd")"
    fi

    export LXD_HOSTFS="${PWD}"
    exec chroot /var/lib/snapd/hostfs "$0" "$@"
fi
cd "${LXD_HOSTFS}"
unset LXD_HOSTFS

export LXD_DIR=${SNAP_COMMON}/lxd/
export EDITOR=vim.tiny
export VISUAL=${EDITOR}
export VIMINIT="source ${SNAP}/etc/vimrc"

exec "${SNAP}/bin/lxc" "$@"
