#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
if [ -d /sys/kernel/security/apparmor ] && [ "$(cat /proc/self/attr/current)" != "unconfined" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
fi

# Move to the right directory
PWD=$(pwd)
if [ "${PWD}" = "/var/lib/snapd/void" ]; then
    PWD="$(readlink -f "/proc/${PPID}/cwd")"
fi
cd "/var/lib/snapd/hostfs/${PWD}" 2>/dev/null || true

# Set the environment
export LXD_DIR=${SNAP_COMMON}/lxd/
export EDITOR=vim.tiny
export VISUAL=${EDITOR}
export VIMINIT="source ${SNAP}/etc/vimrc"

# Run lxc itself
exec "${SNAP}/bin/lxc" "$@"
