#!/bin/sh
if [ "$(id -u)" != "0" ]; then
    echo "" >&2
    echo "\"lxc file mount\" with SSHFS can only be used as root in the LXD snap." >&2
    echo  "For use as a regular user, please use the --connect option instead." >&2
    echo "" >&2
    exit 1
fi

CMD="$(basename "${0}")"
unset LD_LIBRARY_PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

shift 2
SRC="${1}"
shift
DST="$(echo ${1} | sed "s#/var/lib/snapd/hostfs##g")"
shift

exec nsenter -t 1 -m "${CMD}" -o slave "${SRC}" "${DST}" "$@"
