#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
if [ -d /sys/kernel/security/apparmor ] && [ "$(cat /proc/self/attr/current)" != "unconfined" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
fi

# Check if native and snap installed
pid=$(ss -nlpx src "/var/lib/lxd/unix.socket" 2>/dev/null | grep "/var/lib/lxd/unix.socket" | sed -e "s/.*pid=//" -e "s/,.*//g")
if [ "${pid}" -gt 0 ] 2>/dev/null; then
    echo "Error: Both native and snap packages are installed on this system"
    echo "       Run \"lxd.migrate\" to complete your migration to the snap package"
    exit 1
fi

# Guess the real home directory
REAL_HOME="${HOME}"
if [ "${USER:-}" = "root" ] && [ -e "/root" ]; then
    REAL_HOME="/root"
elif [ -n "${USER:-}" ] && [ -e "/home/${USER}" ]; then
    REAL_HOME="/home/${USER}"
fi

# Migrate data if needed
if [ ! -d "${HOME}/.config/lxc" ]; then
    mkdir -p "${HOME}/.config"
    if [ -d "${REAL_HOME}/.config/lxc" ]; then
        cp -r "${REAL_HOME}/.config/lxc" "${HOME}/.config/lxc" || true
    fi
fi

# Set the environment
export LXD_DIR=${LXD_DIR:-"${SNAP_COMMON}/lxd/"}

if [ "${EDITOR:-}" != "nano" ]; then
    export EDITOR=vim.tiny
    if [ -e "${HOME}/.vimrc" ]; then
        export VIMINIT="source ${HOME}/.vimrc"
    else
        export VIMINIT="source ${SNAP}/etc/vimrc"
    fi
fi
export VISUAL=${EDITOR:-}

# Reset all locales as it isn't available in the snap (#29)
LANG=C.UTF-8
export LC_ALL=C.UTF-8

# Add extra binaries to path
export PATH="/run/bin:${PATH}"

LXC="lxc"
if [ -x "${SNAP_COMMON}/lxc.debug" ]; then
    LXC="${SNAP_COMMON}/lxc.debug"
fi

# Run lxc itself
exec "${LXC}" "$@"
