#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
if [ -d /sys/kernel/security/apparmor ] && [ "$(cat /proc/self/attr/current)" != "unconfined" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
fi

# Migrate data if needed
if [ ! -d "${HOME}/.config/lxc" ]; then
    mkdir -p "${HOME}/.config"
    if [ -d "/home/${USER}/.config/lxc" ]; then
        cp -r "/home/${USER}/.config/lxc" "${HOME}/.config/lxc" || true
    elif [ "${USER}" = "root" ] && [ -d "/root/.config/lxc" ]; then
        cp -r "/root/.config/lxc" "${HOME}/.config/lxc" || true
    fi
fi

# Set the environment
export LXD_DIR=${SNAP_COMMON}/lxd/

if [ "${EDITOR:-}" != "nano" ]; then
    export EDITOR=vim.tiny
    export VIMINIT="source ${SNAP}/etc/vimrc"
fi
export VISUAL=${EDITOR:-}

LXC="lxc"
if [ -x "${SNAP_COMMON}/lxc.debug" ]; then
    LXC="${SNAP_COMMON}/lxc.debug"
fi

# Run lxc itself
exec "${LXC}" "$@"
