#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
if [ -d /sys/kernel/security/apparmor ]; then
  label="$(cat /proc/self/attr/current 2>/dev/null)"
  if [ "$label" != "unconfined" ] && [ -n "${label##*(unconfined)}" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
  fi
fi

# Set the environment
export LXD_DIR="${LXD_DIR:-"${SNAP_COMMON}/lxd/"}"
export PATH="/run/bin:${PATH}"

# Reset all locales as it isn't available in the snap (#29)
LANG=C.UTF-8
export LC_ALL=C.UTF-8

# Relocate to storage dir
mkdir -p "${SNAP_COMMON}/lxd-user/"
chmod 0711 "${SNAP_COMMON}/lxd-user/"
cd "${SNAP_COMMON}/lxd-user/"

# Run lxd-user
exec lxd-user
