#!/bin/sh

set -eu

SNAP_CURRENT="$(realpath "${SNAP}/..")/current"
export "${SNAP_CURRENT}"

. "${SNAP_CURRENT}/snap/hooks/common"

ceph_builtin=$(get_bool "$(snapctl get ceph.builtin)")
if ! [ "${ceph_builtin:-"false"}" = "true" ]; then
  ln -snf ${SNAP_DATA}/microceph/conf/ /etc/ceph
fi
