#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
if [ -d /sys/kernel/security/apparmor ]; then
  label="$(cat /proc/self/attr/current 2>/dev/null)"
  if [ "$label" != "unconfined" ] && [ -n "${label##*(unconfined)}" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
  fi
fi

if [ -e "/etc/.lxd_generated" ]; then
    nvidia_container_cli="${SNAP}/bin/nvidia-container-cli"
    backup_file_nvidia_container_cli="${nvidia_container_cli}.bak"

    # Restore from backup if it exists
    if [ -f "${backup_file_nvidia_container_cli}" ]; then
        mv "${backup_file_nvidia_container_cli}" "${nvidia_container_cli}"
        chmod +x "${nvidia_container_cli}"
    else
        # If no backup, recreate the original content
        cat > "${nvidia_container_cli}" << EOF
#!/bin/sh

# Set the root path
exec nvidia-container-cli.real -r /var/lib/snapd/hostfs/ "\$@"
EOF
        chmod +x "${nvidia_container_cli}"
    fi
fi
