#!/bin/sh

set -eu

SNAP_CURRENT="$(realpath "${SNAP}/..")/current"
export "${SNAP_CURRENT}"

. "${SNAP_CURRENT}/snap/hooks/common"

ceph_builtin=$(get_bool "$(snapctl get ceph.builtin)")
if [ "${ceph_builtin:-"false"}" = "true" ]; then
    mkdir -p "${SNAP_COMMON}/ceph"
    ln -snf "${SNAP_COMMON}/ceph" /etc/ceph
else
    ln -snf /var/lib/snapd/hostfs/etc/ceph /etc/ceph
fi
