#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
if [ -d /sys/kernel/security/apparmor ] && [ "$(cat /proc/self/attr/current)" != "unconfined" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
fi

# Unmount potential LXD paths.
for path in "${SNAP_COMMON}/ns/shmounts" "${SNAP_COMMON}/ns/mntns" "${SNAP_COMMON}/ns"; do
    nsenter -t 1 -m umount -l "${path}" >/dev/null 2>&1 || true
done

# Unmount lxcfs.
umount -l "${SNAP_COMMON}/var/lib/lxcfs/" 2>&1 || true

# Stop workaround unit
nsenter -t 1 -m systemctl stop snap.lxd.workaround >/dev/null 2>&1 || true

exit 0
