#!/bin/sh
set -eu

# Re-exec outside of apparmor confinement
if [ -d /sys/kernel/security/apparmor ] && [ "$(cat /proc/self/attr/current)" != "unconfined" ]; then
    exec aa-exec -p unconfined -- "$0" "$@"
fi

# Unmount potential LXD paths.
for path in /var/snap/lxd/common/ns/shmounts /var/snap/lxd/common/ns/mntns /var/snap/lxd/common/ns; do
    nsenter -t 1 -m umount -l "${path}" >/dev/null 2>&1 || true
done

# Stop workaround unit
nsenter -t 1 -m systemctl stop snap.lxd.workaround >/dev/null 2>&1 || true

exit 0
